apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  containers:
  - image: shakti125/shoppingcart:1.2
    name: myshoppingcart
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
