apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: shoppingcart
  name: shoppingcartdata
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
status: {}
